PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE "T_TASK_NOTES"(
[TASK_NOTE_TX] text NOT NULL
,[TASK_NOTE_DT] char(10) NOT NULL
,[TASK_ID] int NOT NULL
, Primary Key(TASK_NOTE_DT,TASK_ID)   
);
COMMIT;
